spring:
  application:
    name: supplier-service

server:
  port: 8010


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/
  instance:
    hostname: localhost